const value1 = 'title';
const value2 = 'author';
const value3 = 'pages';
const value4 = 'language';
const value5 = 'available';
const book = {};
book[value1] = 'Clean Code';
book[value2] = 'Robert C. Martin';
book[value3] = 464;
book[value4] = 'English';
book[value5] = true;
console.log(book);